### ISSUE TITLE
Github support

### ISSUE THREAD

**Issue by cd4ml** [cd4ml/cd4ml#1]
https://github.blog/2019-11-05-self-hosted-runners-for-github-actions-is-now-in-beta/

**Comment by DavidGOrtega** [comment]
![image](https://user-images.githubusercontent.com/414967/70062169-d4329400-15e5-11ea-8dae-9a0043acb7f3.png)


Yesterday I was pretty excited about the Actions done by code. Basically the idea is creating a repo that can then used as an Action. 
However today I see that your runners will be used by people that has forked your repo. Maybe thats good for our purposes but sounds to me pretty bad that we can not control that.

open to discussion

**Comment by DavidGOrtega** [comment]
Closed to experiment exclusively with gocd
